services:
  - type: web
    name: polylance-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    branch: master
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.0
      - key: NETWORK
        value: amoy
      - key: RPC_URL
        value: https://polygon-amoy.g.alchemy.com/v2/xd727FUEtN2c-SPI_yo3B
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: PINATA_API_KEY
        sync: false
      - key: PINATA_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://polylance.codes,https://www.polylance.codes

  - type: web
    name: polylance-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    plan: free
    branch: master
    envVars:
      - key: VITE_API_BASE_URL
        value: https://api.polylance.codes/api
      - key: VITE_RAZORPAY_KEY_ID
        sync: false
      - key: VITE_ALCHEMY_ID
        value: xd727FUEtN2c-SPI_yo3B
      - key: VITE_PARTICLE_PROJECT_ID
        value: 07928a08-6e61-43c2-8ab6-b03e240df39b
      - key: VITE_PARTICLE_CLIENT_KEY
        value: copZES78qEpPmjSFKJLXOYfRqXLfaiVHVRr1gJmP
      - key: VITE_PARTICLE_APP_ID
        value: df654a5d-4d11-451a-9f48-816041124d44
      - key: VITE_BICONOMY_PAYMASTER_URL
        value: mee_5bETq4RwcMcNzcRKVnEDnT
      - key: VITE_BICONOMY_BUNDLER_URL
        value: https://bundler.biconomy.io/api/v2/80002/nJPK7B3ru.dd7f7861-190d-41bd-af80-6877f74b8f44
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
