services:
  - type: web
    name: polylance-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    branch: master
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.0
      - key: NETWORK
        value: amoy
      - key: RPC_URL
        value: https://rpc-amoy.polygon.technology
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromGroup: shared-secrets
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PINATA_API_KEY
        sync: false
      - key: PINATA_SECRET_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://polygon-freelance-marketplace-onf5efcpb.vercel.app

  - type: web
    name: polylance-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    plan: free
    branch: master
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
